export const errorCodes = {
  BAD_REQUEST: 'BAD_REQUEST',
  INVALID_GAME_KEY: 'INVALID_GAME_KEY',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_GAME_MISMATCH: 'TOKEN_GAME_MISMATCH',
  AD_VERIFY_FAILED: 'AD_VERIFY_FAILED'
} as const;
